#docker-compose
version: '3'

services:
  nextjs:
    build: ./
    image: falconlee236/puangfilm-web
    container_name: nextjs
    ports:
      - '3030:3030'
    command: 'npm run start'
    restart: always
    environment:
      - PORT=3030
      - HOSTNAME="0.0.0.0"

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always


# https://medium.com/@priytamk/hosting-a-next-js-application-on-aws-ec2-with-docker-and-ssl-77643515581a