export * from './image-with-description.interface';
export * from './button.interface';
export * from './modal.interface';
export * from './icon.interface';
export * from './frame.interface';
export * from './route.interface';
export * from './previous-page.interface';
export * from './policy.interface';
export * from './image-file.interface';
